version: '3'
services:
  app:
    build:
      context: .
      dockerfile: python/Dockerfile
    ports:
      - "8000:80"
      - "8501:8501" # streamlit
    volumes:
      - ..:/workspace
    
    tty: true 