version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: python/Dockerfile
    ports:
      - "8000:80"
      - "8501:8501" # streamlit
    restart: always
    volumes:
      - ..:/workspace
    tty: true
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    restart: always

volumes:
  db_data:

networks:
  app_network:
